/* Generated by Yosys 0.9+4300 (git sha1 551ef85c, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "arbitro_2_estruct.v:1.1-70.10" *)
module arbitro_2_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, empty, state, pop, push0, push1, push2, push3);
  (* src = "arbitro_2_estruct.v:16.1-24.4" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "arbitro_2_estruct.v:3.11-3.23" *)
  input almost_full0;
  (* src = "arbitro_2_estruct.v:4.11-4.23" *)
  input almost_full1;
  (* src = "arbitro_2_estruct.v:5.11-5.23" *)
  input almost_full2;
  (* src = "arbitro_2_estruct.v:6.11-6.23" *)
  input almost_full3;
  (* src = "arbitro_2_estruct.v:2.11-2.14" *)
  input clk;
  (* src = "arbitro_2_estruct.v:15.11-15.19" *)
  wire [1:0] contador;
  (* src = "arbitro_2_estruct.v:7.11-7.16" *)
  input empty;
  (* src = "arbitro_2_estruct.v:9.16-9.19" *)
  output pop;
  (* src = "arbitro_2_estruct.v:10.16-10.21" *)
  output push0;
  (* src = "arbitro_2_estruct.v:11.16-11.21" *)
  output push1;
  (* src = "arbitro_2_estruct.v:12.16-12.21" *)
  output push2;
  (* src = "arbitro_2_estruct.v:13.16-13.21" *)
  output push3;
  (* src = "arbitro_2_estruct.v:8.17-8.22" *)
  input [3:0] state;
  NOT _09_ (
    .A(state[3]),
    .Y(_01_)
  );
  NOR _10_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_02_)
  );
  NOT _11_ (
    .A(_02_),
    .Y(_03_)
  );
  NAND _12_ (
    .A(_01_),
    .B(state[0]),
    .Y(_04_)
  );
  NOR _13_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  NOT _14_ (
    .A(_05_),
    .Y(_00_)
  );
  NOR _15_ (
    .A(almost_full0),
    .B(almost_full1),
    .Y(_06_)
  );
  NOR _16_ (
    .A(almost_full2),
    .B(almost_full3),
    .Y(_07_)
  );
  NAND _17_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  NOT _18_ (
    .A(_08_),
    .Y(pop)
  );
  NAND _19_ (
    .A(empty),
    .B(_05_),
    .Y(push0)
  );
  (* src = "arbitro_2_estruct.v:16.1-24.4" *)
  DFF _20_ (
    .C(clk),
    .D(_00_),
    .Q(pop)
  );
  assign contador = 2'h0;
  assign push1 = 1'h0;
  assign push2 = 1'h0;
  assign push3 = 1'h0;
endmodule
