/* Generated by Yosys 0.9+4300 (git sha1 551ef85c, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "arbitro_2_estruct.v:1.1-79.10" *)
module arbitro_2_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, empty, state, pop, push0, push1, push2, push3);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* src = "arbitro_2_estruct.v:3.11-3.23" *)
  input almost_full0;
  (* src = "arbitro_2_estruct.v:4.11-4.23" *)
  input almost_full1;
  (* src = "arbitro_2_estruct.v:5.11-5.23" *)
  input almost_full2;
  (* src = "arbitro_2_estruct.v:6.11-6.23" *)
  input almost_full3;
  (* src = "arbitro_2_estruct.v:2.11-2.14" *)
  input clk;
  (* src = "arbitro_2_estruct.v:15.11-15.19" *)
  wire [1:0] contador;
  (* src = "arbitro_2_estruct.v:7.11-7.16" *)
  input empty;
  (* src = "arbitro_2_estruct.v:9.16-9.19" *)
  output pop;
  (* src = "arbitro_2_estruct.v:10.16-10.21" *)
  output push0;
  (* src = "arbitro_2_estruct.v:11.16-11.21" *)
  output push1;
  (* src = "arbitro_2_estruct.v:12.16-12.21" *)
  output push2;
  (* src = "arbitro_2_estruct.v:13.16-13.21" *)
  output push3;
  (* src = "arbitro_2_estruct.v:8.17-8.22" *)
  input [3:0] state;
  NOT _29_ (
    .A(contador[1]),
    .Y(_02_)
  );
  NOT _30_ (
    .A(contador[0]),
    .Y(_03_)
  );
  NOT _31_ (
    .A(state[0]),
    .Y(_04_)
  );
  NOT _32_ (
    .A(state[1]),
    .Y(_05_)
  );
  NOT _33_ (
    .A(empty),
    .Y(_06_)
  );
  NOT _34_ (
    .A(almost_full3),
    .Y(_07_)
  );
  NOR _35_ (
    .A(_04_),
    .B(state[1]),
    .Y(_08_)
  );
  NAND _36_ (
    .A(state[0]),
    .B(_05_),
    .Y(_09_)
  );
  NOR _37_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_10_)
  );
  NOT _38_ (
    .A(_10_),
    .Y(_11_)
  );
  NOR _39_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  NAND _40_ (
    .A(_08_),
    .B(_10_),
    .Y(_13_)
  );
  NAND _41_ (
    .A(_02_),
    .B(contador[0]),
    .Y(_14_)
  );
  NAND _42_ (
    .A(empty),
    .B(_14_),
    .Y(_15_)
  );
  NAND _43_ (
    .A(contador[0]),
    .B(_06_),
    .Y(_16_)
  );
  NAND _44_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  NOR _45_ (
    .A(_12_),
    .B(_17_),
    .Y(_00_)
  );
  NOR _46_ (
    .A(empty),
    .B(almost_full0),
    .Y(_18_)
  );
  NOT _47_ (
    .A(_18_),
    .Y(_19_)
  );
  NOR _48_ (
    .A(almost_full1),
    .B(almost_full2),
    .Y(_20_)
  );
  NAND _49_ (
    .A(_07_),
    .B(_20_),
    .Y(_21_)
  );
  NOR _50_ (
    .A(_19_),
    .B(_21_),
    .Y(pop)
  );
  NAND _51_ (
    .A(_06_),
    .B(_13_),
    .Y(_22_)
  );
  NAND _52_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_23_)
  );
  NOR _53_ (
    .A(_22_),
    .B(_23_),
    .Y(push3)
  );
  NAND _54_ (
    .A(contador[1]),
    .B(_03_),
    .Y(_24_)
  );
  NOR _55_ (
    .A(_22_),
    .B(_24_),
    .Y(push2)
  );
  NOR _56_ (
    .A(_14_),
    .B(_22_),
    .Y(push1)
  );
  NOR _57_ (
    .A(contador[1]),
    .B(contador[0]),
    .Y(_25_)
  );
  NOT _58_ (
    .A(_25_),
    .Y(_26_)
  );
  NOR _59_ (
    .A(_22_),
    .B(_26_),
    .Y(push0)
  );
  NAND _60_ (
    .A(_02_),
    .B(_16_),
    .Y(_27_)
  );
  NAND _61_ (
    .A(_23_),
    .B(_27_),
    .Y(_28_)
  );
  NOR _62_ (
    .A(_12_),
    .B(_28_),
    .Y(_01_)
  );
  (* src = "arbitro_2_estruct.v:66.1-77.4" *)
  DFF _63_ (
    .C(clk),
    .D(_00_),
    .Q(contador[0])
  );
  (* src = "arbitro_2_estruct.v:66.1-77.4" *)
  DFF _64_ (
    .C(clk),
    .D(_01_),
    .Q(contador[1])
  );
endmodule
