/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbitro_2_estruct.v:1" *)
module arbitro_2_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, empty, state, pop, push0, push1, push2, push3);
  (* src = "arbitro_2_estruct.v:66" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "arbitro_2_estruct.v:3" *)
  input almost_full0;
  (* src = "arbitro_2_estruct.v:4" *)
  input almost_full1;
  (* src = "arbitro_2_estruct.v:5" *)
  input almost_full2;
  (* src = "arbitro_2_estruct.v:6" *)
  input almost_full3;
  (* src = "arbitro_2_estruct.v:2" *)
  input clk;
  (* src = "arbitro_2_estruct.v:15" *)
  wire [1:0] contador;
  (* src = "arbitro_2_estruct.v:7" *)
  input empty;
  (* src = "arbitro_2_estruct.v:9" *)
  output pop;
  (* src = "arbitro_2_estruct.v:10" *)
  output push0;
  (* src = "arbitro_2_estruct.v:11" *)
  output push1;
  (* src = "arbitro_2_estruct.v:12" *)
  output push2;
  (* src = "arbitro_2_estruct.v:13" *)
  output push3;
  (* src = "arbitro_2_estruct.v:8" *)
  input [3:0] state;
  NOT _23_ (
    .A(contador[0]),
    .Y(_01_)
  );
  NOT _24_ (
    .A(empty),
    .Y(_02_)
  );
  NOT _25_ (
    .A(almost_full3),
    .Y(_03_)
  );
  NOT _26_ (
    .A(state[0]),
    .Y(_04_)
  );
  NAND _27_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_05_)
  );
  NOR _28_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_06_)
  );
  NOR _29_ (
    .A(state[3]),
    .B(_04_),
    .Y(_07_)
  );
  NAND _30_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  NAND _31_ (
    .A(_05_),
    .B(_08_),
    .Y(_09_)
  );
  NAND _32_ (
    .A(contador[0]),
    .B(_02_),
    .Y(_10_)
  );
  NOT _33_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _34_ (
    .A(_01_),
    .B(empty),
    .Y(_12_)
  );
  NAND _35_ (
    .A(_10_),
    .B(_12_),
    .Y(_13_)
  );
  NOR _36_ (
    .A(_09_),
    .B(_13_),
    .Y(_00_[0])
  );
  NOR _37_ (
    .A(contador[1]),
    .B(_11_),
    .Y(_14_)
  );
  NOR _38_ (
    .A(_09_),
    .B(_14_),
    .Y(_00_[1])
  );
  NOR _39_ (
    .A(empty),
    .B(almost_full0),
    .Y(_15_)
  );
  NOT _40_ (
    .A(_15_),
    .Y(_16_)
  );
  NOR _41_ (
    .A(almost_full1),
    .B(almost_full2),
    .Y(_17_)
  );
  NAND _42_ (
    .A(_03_),
    .B(_17_),
    .Y(_18_)
  );
  NOR _43_ (
    .A(_16_),
    .B(_18_),
    .Y(pop)
  );
  NAND _44_ (
    .A(_02_),
    .B(_08_),
    .Y(_19_)
  );
  NOR _45_ (
    .A(_09_),
    .B(_10_),
    .Y(push1)
  );
  NOR _46_ (
    .A(_05_),
    .B(_19_),
    .Y(push3)
  );
  NAND _47_ (
    .A(_01_),
    .B(contador[1]),
    .Y(_20_)
  );
  NOR _48_ (
    .A(_19_),
    .B(_20_),
    .Y(push2)
  );
  NOR _49_ (
    .A(contador[0]),
    .B(contador[1]),
    .Y(_21_)
  );
  NOT _50_ (
    .A(_21_),
    .Y(_22_)
  );
  NOR _51_ (
    .A(_19_),
    .B(_22_),
    .Y(push0)
  );
  (* src = "arbitro_2_estruct.v:66" *)
  DFF _52_ (
    .C(clk),
    .D(_00_[0]),
    .Q(contador[0])
  );
  (* src = "arbitro_2_estruct.v:66" *)
  DFF _53_ (
    .C(clk),
    .D(_00_[1]),
    .Q(contador[1])
  );
endmodule
