/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbitro_1_estruct.v:1" *)
module arbitro_1_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, empty0, empty1, empty2, empty3, dest, valid_0, valid_1, valid_2, valid_3, state, pop0, pop1, pop2, pop3, push0, push1, push2, push3);
  (* src = "arbitro_1_estruct.v:89" *)
  wire [2:0] _000_;
  (* src = "arbitro_1_estruct.v:89" *)
  wire [2:0] _001_;
  (* src = "arbitro_1_estruct.v:89" *)
  wire [2:0] _002_;
  (* src = "arbitro_1_estruct.v:89" *)
  wire [2:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  (* src = "arbitro_1_estruct.v:3" *)
  input almost_full0;
  (* src = "arbitro_1_estruct.v:4" *)
  input almost_full1;
  (* src = "arbitro_1_estruct.v:5" *)
  input almost_full2;
  (* src = "arbitro_1_estruct.v:6" *)
  input almost_full3;
  (* src = "arbitro_1_estruct.v:2" *)
  input clk;
  (* src = "arbitro_1_estruct.v:26" *)
  wire [2:0] contador0;
  (* src = "arbitro_1_estruct.v:27" *)
  wire [2:0] contador1;
  (* src = "arbitro_1_estruct.v:28" *)
  wire [2:0] contador2;
  (* src = "arbitro_1_estruct.v:29" *)
  wire [2:0] contador3;
  (* src = "arbitro_1_estruct.v:11" *)
  input [1:0] dest;
  (* src = "arbitro_1_estruct.v:7" *)
  input empty0;
  (* src = "arbitro_1_estruct.v:8" *)
  input empty1;
  (* src = "arbitro_1_estruct.v:9" *)
  input empty2;
  (* src = "arbitro_1_estruct.v:10" *)
  input empty3;
  (* src = "arbitro_1_estruct.v:17" *)
  output pop0;
  (* src = "arbitro_1_estruct.v:18" *)
  output pop1;
  (* src = "arbitro_1_estruct.v:19" *)
  output pop2;
  (* src = "arbitro_1_estruct.v:20" *)
  output pop3;
  (* src = "arbitro_1_estruct.v:21" *)
  output push0;
  (* src = "arbitro_1_estruct.v:22" *)
  output push1;
  (* src = "arbitro_1_estruct.v:23" *)
  output push2;
  (* src = "arbitro_1_estruct.v:24" *)
  output push3;
  (* src = "arbitro_1_estruct.v:16" *)
  input [3:0] state;
  (* src = "arbitro_1_estruct.v:12" *)
  input valid_0;
  (* src = "arbitro_1_estruct.v:13" *)
  input valid_1;
  (* src = "arbitro_1_estruct.v:14" *)
  input valid_2;
  (* src = "arbitro_1_estruct.v:15" *)
  input valid_3;
  NOT _076_ (
    .A(dest[0]),
    .Y(_031_)
  );
  NOT _077_ (
    .A(state[3]),
    .Y(_032_)
  );
  NOT _078_ (
    .A(dest[1]),
    .Y(_033_)
  );
  NOT _079_ (
    .A(contador1[0]),
    .Y(_034_)
  );
  NOT _080_ (
    .A(contador1[2]),
    .Y(_035_)
  );
  NOT _081_ (
    .A(contador2[0]),
    .Y(_036_)
  );
  NOT _082_ (
    .A(contador2[2]),
    .Y(_037_)
  );
  NOT _083_ (
    .A(contador0[1]),
    .Y(_038_)
  );
  NOT _084_ (
    .A(state[0]),
    .Y(_039_)
  );
  NAND _085_ (
    .A(contador1[0]),
    .B(contador1[1]),
    .Y(_040_)
  );
  NOR _086_ (
    .A(contador1[2]),
    .B(empty1),
    .Y(_041_)
  );
  NAND _087_ (
    .A(_035_),
    .B(_040_),
    .Y(_042_)
  );
  NOR _088_ (
    .A(empty1),
    .B(_042_),
    .Y(_043_)
  );
  NAND _089_ (
    .A(_040_),
    .B(_041_),
    .Y(_044_)
  );
  NOR _090_ (
    .A(almost_full2),
    .B(almost_full0),
    .Y(_045_)
  );
  NOR _091_ (
    .A(almost_full1),
    .B(almost_full3),
    .Y(_046_)
  );
  NAND _092_ (
    .A(_045_),
    .B(_046_),
    .Y(_047_)
  );
  NOT _093_ (
    .A(_047_),
    .Y(_048_)
  );
  NOR _094_ (
    .A(state[1]),
    .B(state[2]),
    .Y(_049_)
  );
  NOT _095_ (
    .A(_049_),
    .Y(_050_)
  );
  NOR _096_ (
    .A(state[3]),
    .B(_039_),
    .Y(_051_)
  );
  NAND _097_ (
    .A(_032_),
    .B(state[0]),
    .Y(_052_)
  );
  NOR _098_ (
    .A(_050_),
    .B(_052_),
    .Y(_053_)
  );
  NAND _099_ (
    .A(_049_),
    .B(_051_),
    .Y(_054_)
  );
  NOR _100_ (
    .A(_047_),
    .B(_053_),
    .Y(_055_)
  );
  NAND _101_ (
    .A(_048_),
    .B(_054_),
    .Y(_056_)
  );
  NOR _102_ (
    .A(_043_),
    .B(_056_),
    .Y(_057_)
  );
  NAND _103_ (
    .A(_044_),
    .B(_055_),
    .Y(_058_)
  );
  NOR _104_ (
    .A(contador2[1]),
    .B(empty2),
    .Y(_059_)
  );
  NAND _105_ (
    .A(_037_),
    .B(_059_),
    .Y(_060_)
  );
  NOR _106_ (
    .A(contador0[2]),
    .B(empty0),
    .Y(_061_)
  );
  NOT _107_ (
    .A(_061_),
    .Y(_062_)
  );
  NOR _108_ (
    .A(contador3[0]),
    .B(contador3[1]),
    .Y(_063_)
  );
  NOR _109_ (
    .A(contador3[2]),
    .B(empty3),
    .Y(_064_)
  );
  NAND _110_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _111_ (
    .A(_061_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _112_ (
    .A(_060_),
    .B(_066_),
    .Y(_067_)
  );
  NOR _113_ (
    .A(_058_),
    .B(_067_),
    .Y(pop3)
  );
  NOT _114_ (
    .A(pop3),
    .Y(_068_)
  );
  NOR _115_ (
    .A(_044_),
    .B(_061_),
    .Y(_069_)
  );
  NAND _116_ (
    .A(_055_),
    .B(_069_),
    .Y(_070_)
  );
  NOT _117_ (
    .A(_070_),
    .Y(pop1)
  );
  NOR _118_ (
    .A(_060_),
    .B(_061_),
    .Y(_071_)
  );
  NAND _119_ (
    .A(_057_),
    .B(_071_),
    .Y(_072_)
  );
  NOT _120_ (
    .A(_072_),
    .Y(pop2)
  );
  NOR _121_ (
    .A(_056_),
    .B(_062_),
    .Y(pop0)
  );
  NAND _122_ (
    .A(contador3[0]),
    .B(_054_),
    .Y(_073_)
  );
  NOR _123_ (
    .A(pop0),
    .B(_073_),
    .Y(_074_)
  );
  NOR _124_ (
    .A(pop3),
    .B(_074_),
    .Y(_075_)
  );
  NOT _125_ (
    .A(_075_),
    .Y(_003_[0])
  );
  NAND _126_ (
    .A(contador3[1]),
    .B(_054_),
    .Y(_004_)
  );
  NOR _127_ (
    .A(pop0),
    .B(_004_),
    .Y(_003_[1])
  );
  NAND _128_ (
    .A(contador3[2]),
    .B(_054_),
    .Y(_005_)
  );
  NOR _129_ (
    .A(pop0),
    .B(_005_),
    .Y(_003_[2])
  );
  NOR _130_ (
    .A(_053_),
    .B(pop3),
    .Y(_006_)
  );
  NAND _131_ (
    .A(_054_),
    .B(_068_),
    .Y(_007_)
  );
  NOR _132_ (
    .A(contador0[0]),
    .B(pop0),
    .Y(_008_)
  );
  NAND _133_ (
    .A(contador0[0]),
    .B(pop0),
    .Y(_009_)
  );
  NAND _134_ (
    .A(_006_),
    .B(_009_),
    .Y(_010_)
  );
  NOR _135_ (
    .A(_008_),
    .B(_010_),
    .Y(_000_[0])
  );
  NOR _136_ (
    .A(_038_),
    .B(_009_),
    .Y(_011_)
  );
  NAND _137_ (
    .A(_038_),
    .B(_009_),
    .Y(_012_)
  );
  NAND _138_ (
    .A(_006_),
    .B(_012_),
    .Y(_013_)
  );
  NOR _139_ (
    .A(_011_),
    .B(_013_),
    .Y(_000_[1])
  );
  NOR _140_ (
    .A(contador0[2]),
    .B(_011_),
    .Y(_014_)
  );
  NOR _141_ (
    .A(_007_),
    .B(_014_),
    .Y(_000_[2])
  );
  NOR _142_ (
    .A(_036_),
    .B(_072_),
    .Y(_015_)
  );
  NAND _143_ (
    .A(_036_),
    .B(_072_),
    .Y(_016_)
  );
  NAND _144_ (
    .A(_006_),
    .B(_016_),
    .Y(_017_)
  );
  NOR _145_ (
    .A(_015_),
    .B(_017_),
    .Y(_002_[0])
  );
  NOR _146_ (
    .A(contador2[1]),
    .B(_015_),
    .Y(_018_)
  );
  NOR _147_ (
    .A(_007_),
    .B(_018_),
    .Y(_002_[1])
  );
  NOR _148_ (
    .A(_037_),
    .B(_007_),
    .Y(_002_[2])
  );
  NOR _149_ (
    .A(_034_),
    .B(_070_),
    .Y(_019_)
  );
  NAND _150_ (
    .A(_034_),
    .B(_070_),
    .Y(_020_)
  );
  NAND _151_ (
    .A(_006_),
    .B(_020_),
    .Y(_021_)
  );
  NOR _152_ (
    .A(_019_),
    .B(_021_),
    .Y(_001_[0])
  );
  NOR _153_ (
    .A(contador1[1]),
    .B(_019_),
    .Y(_022_)
  );
  NOR _154_ (
    .A(_007_),
    .B(_022_),
    .Y(_001_[1])
  );
  NOR _155_ (
    .A(_035_),
    .B(_007_),
    .Y(_001_[2])
  );
  NAND _156_ (
    .A(_033_),
    .B(_048_),
    .Y(_023_)
  );
  NAND _157_ (
    .A(dest[0]),
    .B(valid_1),
    .Y(_024_)
  );
  NOR _158_ (
    .A(_023_),
    .B(_024_),
    .Y(push1)
  );
  NAND _159_ (
    .A(dest[0]),
    .B(dest[1]),
    .Y(_025_)
  );
  NOT _160_ (
    .A(_025_),
    .Y(_026_)
  );
  NAND _161_ (
    .A(valid_3),
    .B(_026_),
    .Y(_027_)
  );
  NOR _162_ (
    .A(_047_),
    .B(_027_),
    .Y(push3)
  );
  NOR _163_ (
    .A(dest[0]),
    .B(_033_),
    .Y(_028_)
  );
  NAND _164_ (
    .A(valid_2),
    .B(_028_),
    .Y(_029_)
  );
  NOR _165_ (
    .A(_047_),
    .B(_029_),
    .Y(push2)
  );
  NAND _166_ (
    .A(_031_),
    .B(valid_0),
    .Y(_030_)
  );
  NOR _167_ (
    .A(_023_),
    .B(_030_),
    .Y(push0)
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _168_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador0[0])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _169_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador0[1])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _170_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador0[2])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _171_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contador1[0])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _172_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contador1[1])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _173_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contador1[2])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _174_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contador2[0])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _175_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contador2[1])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _176_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contador2[2])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _177_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contador3[0])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _178_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contador3[1])
  );
  (* src = "arbitro_1_estruct.v:89" *)
  DFF _179_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contador3[2])
  );
endmodule
