/* Generated by Yosys 0.9+4300 (git sha1 551ef85c, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "arbitro_1_estruct.v:1.1-116.10" *)
module arbitro_1_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, empty0, empty1, empty2, empty3, dest, valid_0, valid_1, valid_2, valid_3, state, pop0, pop1, pop2, pop3, push0, push1, push2, push3);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "arbitro_1_estruct.v:3.11-3.23" *)
  input almost_full0;
  (* src = "arbitro_1_estruct.v:4.11-4.23" *)
  input almost_full1;
  (* src = "arbitro_1_estruct.v:5.11-5.23" *)
  input almost_full2;
  (* src = "arbitro_1_estruct.v:6.11-6.23" *)
  input almost_full3;
  (* src = "arbitro_1_estruct.v:2.11-2.14" *)
  input clk;
  (* src = "arbitro_1_estruct.v:26.11-26.20" *)
  wire [2:0] contador0;
  (* src = "arbitro_1_estruct.v:27.11-27.20" *)
  wire [2:0] contador1;
  (* src = "arbitro_1_estruct.v:28.11-28.20" *)
  wire [2:0] contador2;
  (* src = "arbitro_1_estruct.v:29.11-29.20" *)
  wire [2:0] contador3;
  (* src = "arbitro_1_estruct.v:11.21-11.25" *)
  input [1:0] dest;
  (* src = "arbitro_1_estruct.v:7.11-7.17" *)
  input empty0;
  (* src = "arbitro_1_estruct.v:8.11-8.17" *)
  input empty1;
  (* src = "arbitro_1_estruct.v:9.11-9.17" *)
  input empty2;
  (* src = "arbitro_1_estruct.v:10.11-10.17" *)
  input empty3;
  (* src = "arbitro_1_estruct.v:17.16-17.20" *)
  output pop0;
  (* src = "arbitro_1_estruct.v:18.16-18.20" *)
  output pop1;
  (* src = "arbitro_1_estruct.v:19.16-19.20" *)
  output pop2;
  (* src = "arbitro_1_estruct.v:20.16-20.20" *)
  output pop3;
  (* src = "arbitro_1_estruct.v:21.16-21.21" *)
  output push0;
  (* src = "arbitro_1_estruct.v:22.16-22.21" *)
  output push1;
  (* src = "arbitro_1_estruct.v:23.16-23.21" *)
  output push2;
  (* src = "arbitro_1_estruct.v:24.16-24.21" *)
  output push3;
  (* src = "arbitro_1_estruct.v:16.17-16.22" *)
  input [3:0] state;
  (* src = "arbitro_1_estruct.v:12.11-12.18" *)
  input valid_0;
  (* src = "arbitro_1_estruct.v:13.11-13.18" *)
  input valid_1;
  (* src = "arbitro_1_estruct.v:14.11-14.18" *)
  input valid_2;
  (* src = "arbitro_1_estruct.v:15.11-15.18" *)
  input valid_3;
  NOT _086_ (
    .A(contador2[2]),
    .Y(_040_)
  );
  NOT _087_ (
    .A(contador2[0]),
    .Y(_041_)
  );
  NOT _088_ (
    .A(contador0[1]),
    .Y(_042_)
  );
  NOT _089_ (
    .A(contador1[2]),
    .Y(_043_)
  );
  NOT _090_ (
    .A(contador1[0]),
    .Y(_044_)
  );
  NOT _091_ (
    .A(state[0]),
    .Y(_045_)
  );
  NOT _092_ (
    .A(dest[0]),
    .Y(_046_)
  );
  NOT _093_ (
    .A(state[1]),
    .Y(_047_)
  );
  NOT _094_ (
    .A(valid_2),
    .Y(_048_)
  );
  NOT _095_ (
    .A(empty2),
    .Y(_049_)
  );
  NAND _096_ (
    .A(contador1[1]),
    .B(contador1[0]),
    .Y(_050_)
  );
  NOR _097_ (
    .A(contador1[2]),
    .B(empty1),
    .Y(_051_)
  );
  NAND _098_ (
    .A(_043_),
    .B(_050_),
    .Y(_052_)
  );
  NOR _099_ (
    .A(empty1),
    .B(_052_),
    .Y(_053_)
  );
  NAND _100_ (
    .A(_050_),
    .B(_051_),
    .Y(_054_)
  );
  NOR _101_ (
    .A(almost_full0),
    .B(almost_full1),
    .Y(_055_)
  );
  NOR _102_ (
    .A(almost_full2),
    .B(almost_full3),
    .Y(_056_)
  );
  NAND _103_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOT _104_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR _105_ (
    .A(_045_),
    .B(state[1]),
    .Y(_059_)
  );
  NAND _106_ (
    .A(state[0]),
    .B(_047_),
    .Y(_060_)
  );
  NOR _107_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_061_)
  );
  NOT _108_ (
    .A(_061_),
    .Y(_062_)
  );
  NOR _109_ (
    .A(_060_),
    .B(_062_),
    .Y(_063_)
  );
  NAND _110_ (
    .A(_059_),
    .B(_061_),
    .Y(_064_)
  );
  NOR _111_ (
    .A(_057_),
    .B(_063_),
    .Y(_065_)
  );
  NAND _112_ (
    .A(_058_),
    .B(_064_),
    .Y(_066_)
  );
  NOR _113_ (
    .A(_053_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _114_ (
    .A(_054_),
    .B(_065_),
    .Y(_068_)
  );
  NOR _115_ (
    .A(contador2[2]),
    .B(contador2[1]),
    .Y(_069_)
  );
  NAND _116_ (
    .A(_049_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _117_ (
    .A(contador0[2]),
    .B(empty0),
    .Y(_071_)
  );
  NOT _118_ (
    .A(_071_),
    .Y(_072_)
  );
  NOR _119_ (
    .A(_070_),
    .B(_071_),
    .Y(_073_)
  );
  NAND _120_ (
    .A(_067_),
    .B(_073_),
    .Y(_074_)
  );
  NOT _121_ (
    .A(_074_),
    .Y(pop2)
  );
  NOR _122_ (
    .A(_041_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _123_ (
    .A(contador2[1]),
    .B(_075_),
    .Y(_076_)
  );
  NOR _124_ (
    .A(contador3[2]),
    .B(contador3[1]),
    .Y(_077_)
  );
  NOR _125_ (
    .A(contador3[0]),
    .B(empty3),
    .Y(_078_)
  );
  NAND _126_ (
    .A(_077_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _127_ (
    .A(_071_),
    .B(_079_),
    .Y(_080_)
  );
  NAND _128_ (
    .A(_070_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _129_ (
    .A(_068_),
    .B(_081_),
    .Y(pop3)
  );
  NOT _130_ (
    .A(pop3),
    .Y(_082_)
  );
  NOR _131_ (
    .A(_063_),
    .B(pop3),
    .Y(_083_)
  );
  NAND _132_ (
    .A(_064_),
    .B(_082_),
    .Y(_084_)
  );
  NOR _133_ (
    .A(_076_),
    .B(_084_),
    .Y(_010_)
  );
  NAND _134_ (
    .A(_041_),
    .B(_074_),
    .Y(_085_)
  );
  NAND _135_ (
    .A(_083_),
    .B(_085_),
    .Y(_012_)
  );
  NOR _136_ (
    .A(_075_),
    .B(_012_),
    .Y(_009_)
  );
  NOR _137_ (
    .A(_066_),
    .B(_072_),
    .Y(pop0)
  );
  NAND _138_ (
    .A(contador0[0]),
    .B(pop0),
    .Y(_013_)
  );
  NOR _139_ (
    .A(_042_),
    .B(_013_),
    .Y(_014_)
  );
  NOR _140_ (
    .A(contador0[2]),
    .B(_014_),
    .Y(_015_)
  );
  NOR _141_ (
    .A(_084_),
    .B(_015_),
    .Y(_008_)
  );
  NAND _142_ (
    .A(_042_),
    .B(_013_),
    .Y(_016_)
  );
  NAND _143_ (
    .A(_083_),
    .B(_016_),
    .Y(_017_)
  );
  NOR _144_ (
    .A(_014_),
    .B(_017_),
    .Y(_007_)
  );
  NOR _145_ (
    .A(contador0[0]),
    .B(pop0),
    .Y(_018_)
  );
  NOT _146_ (
    .A(_018_),
    .Y(_019_)
  );
  NAND _147_ (
    .A(_013_),
    .B(_019_),
    .Y(_020_)
  );
  NOR _148_ (
    .A(_084_),
    .B(_020_),
    .Y(_006_)
  );
  NOR _149_ (
    .A(_043_),
    .B(_084_),
    .Y(_005_)
  );
  NOR _150_ (
    .A(_054_),
    .B(_071_),
    .Y(_021_)
  );
  NAND _151_ (
    .A(_065_),
    .B(_021_),
    .Y(_022_)
  );
  NOT _152_ (
    .A(_022_),
    .Y(pop1)
  );
  NOR _153_ (
    .A(_044_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _154_ (
    .A(contador1[1]),
    .B(_023_),
    .Y(_024_)
  );
  NOR _155_ (
    .A(_084_),
    .B(_024_),
    .Y(_004_)
  );
  NAND _156_ (
    .A(_044_),
    .B(_022_),
    .Y(_025_)
  );
  NAND _157_ (
    .A(_083_),
    .B(_025_),
    .Y(_026_)
  );
  NOR _158_ (
    .A(_023_),
    .B(_026_),
    .Y(_003_)
  );
  NAND _159_ (
    .A(contador3[2]),
    .B(_064_),
    .Y(_027_)
  );
  NOR _160_ (
    .A(pop0),
    .B(_027_),
    .Y(_002_)
  );
  NAND _161_ (
    .A(contador3[1]),
    .B(_064_),
    .Y(_028_)
  );
  NOR _162_ (
    .A(pop0),
    .B(_028_),
    .Y(_001_)
  );
  NAND _163_ (
    .A(contador3[0]),
    .B(_064_),
    .Y(_029_)
  );
  NOR _164_ (
    .A(pop0),
    .B(_029_),
    .Y(_030_)
  );
  NOR _165_ (
    .A(pop3),
    .B(_030_),
    .Y(_031_)
  );
  NOT _166_ (
    .A(_031_),
    .Y(_000_)
  );
  NAND _167_ (
    .A(dest[1]),
    .B(dest[0]),
    .Y(_032_)
  );
  NOT _168_ (
    .A(_032_),
    .Y(_033_)
  );
  NAND _169_ (
    .A(valid_3),
    .B(_033_),
    .Y(_034_)
  );
  NOR _170_ (
    .A(_057_),
    .B(_034_),
    .Y(push3)
  );
  NOR _171_ (
    .A(dest[0]),
    .B(_057_),
    .Y(_035_)
  );
  NAND _172_ (
    .A(dest[1]),
    .B(_035_),
    .Y(_036_)
  );
  NOR _173_ (
    .A(_048_),
    .B(_036_),
    .Y(push2)
  );
  NOR _174_ (
    .A(dest[1]),
    .B(_046_),
    .Y(_037_)
  );
  NAND _175_ (
    .A(valid_1),
    .B(_037_),
    .Y(_038_)
  );
  NOR _176_ (
    .A(_057_),
    .B(_038_),
    .Y(push1)
  );
  NAND _177_ (
    .A(valid_0),
    .B(_035_),
    .Y(_039_)
  );
  NOR _178_ (
    .A(dest[1]),
    .B(_039_),
    .Y(push0)
  );
  NOR _179_ (
    .A(_040_),
    .B(_084_),
    .Y(_011_)
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _180_ (
    .C(clk),
    .D(_000_),
    .Q(contador3[0])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _181_ (
    .C(clk),
    .D(_001_),
    .Q(contador3[1])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _182_ (
    .C(clk),
    .D(_002_),
    .Q(contador3[2])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _183_ (
    .C(clk),
    .D(_003_),
    .Q(contador1[0])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _184_ (
    .C(clk),
    .D(_004_),
    .Q(contador1[1])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _185_ (
    .C(clk),
    .D(_005_),
    .Q(contador1[2])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _186_ (
    .C(clk),
    .D(_006_),
    .Q(contador0[0])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _187_ (
    .C(clk),
    .D(_007_),
    .Q(contador0[1])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _188_ (
    .C(clk),
    .D(_008_),
    .Q(contador0[2])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _189_ (
    .C(clk),
    .D(_009_),
    .Q(contador2[0])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _190_ (
    .C(clk),
    .D(_010_),
    .Q(contador2[1])
  );
  (* src = "arbitro_1_estruct.v:89.1-114.4" *)
  DFF _191_ (
    .C(clk),
    .D(_011_),
    .Q(contador2[2])
  );
endmodule
