/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "arbitro_estruct.v:1" *)
module arbitro_estruct(clk, almost_full0, almost_full1, almost_full2, almost_full3, empty0_orange, empty1_orange, empty2_orange, empty3_orange, empty0_purple, empty1_purple, empty2_purple, empty3_purple, state, push, pop0, pop1, pop2, pop3, empties);
  (* src = "arbitro_estruct.v:24" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "arbitro_estruct.v:3" *)
  input almost_full0;
  (* src = "arbitro_estruct.v:4" *)
  input almost_full1;
  (* src = "arbitro_estruct.v:5" *)
  input almost_full2;
  (* src = "arbitro_estruct.v:6" *)
  input almost_full3;
  (* src = "arbitro_estruct.v:2" *)
  input clk;
  (* src = "arbitro_estruct.v:21" *)
  output [7:0] empties;
  (* src = "arbitro_estruct.v:7" *)
  input empty0_orange;
  (* src = "arbitro_estruct.v:11" *)
  input empty0_purple;
  (* src = "arbitro_estruct.v:8" *)
  input empty1_orange;
  (* src = "arbitro_estruct.v:12" *)
  input empty1_purple;
  (* src = "arbitro_estruct.v:9" *)
  input empty2_orange;
  (* src = "arbitro_estruct.v:13" *)
  input empty2_purple;
  (* src = "arbitro_estruct.v:10" *)
  input empty3_orange;
  (* src = "arbitro_estruct.v:14" *)
  input empty3_purple;
  (* src = "arbitro_estruct.v:17" *)
  output pop0;
  (* src = "arbitro_estruct.v:18" *)
  output pop1;
  (* src = "arbitro_estruct.v:19" *)
  output pop2;
  (* src = "arbitro_estruct.v:20" *)
  output pop3;
  (* src = "arbitro_estruct.v:16" *)
  output push;
  (* src = "arbitro_estruct.v:15" *)
  input [3:0] state;
  NOT _22_ (
    .A(empty3_purple),
    .Y(_01_)
  );
  NOT _23_ (
    .A(empty2_purple),
    .Y(_02_)
  );
  NOT _24_ (
    .A(empty1_purple),
    .Y(_03_)
  );
  NOT _25_ (
    .A(empty2_orange),
    .Y(_04_)
  );
  NOT _26_ (
    .A(empty0_purple),
    .Y(_05_)
  );
  NOT _27_ (
    .A(empty3_orange),
    .Y(_06_)
  );
  NOT _28_ (
    .A(empty1_orange),
    .Y(_07_)
  );
  NOT _29_ (
    .A(empty0_orange),
    .Y(_08_)
  );
  NOT _30_ (
    .A(state[1]),
    .Y(_09_)
  );
  NOR _31_ (
    .A(state[2]),
    .B(state[3]),
    .Y(_10_)
  );
  NOT _32_ (
    .A(_10_),
    .Y(_11_)
  );
  NAND _33_ (
    .A(_09_),
    .B(state[0]),
    .Y(_12_)
  );
  NOR _34_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  NOT _35_ (
    .A(_13_),
    .Y(_00_)
  );
  NOR _36_ (
    .A(_01_),
    .B(_13_),
    .Y(empties[7])
  );
  NOR _37_ (
    .A(_02_),
    .B(_13_),
    .Y(empties[6])
  );
  NOR _38_ (
    .A(_03_),
    .B(_13_),
    .Y(empties[5])
  );
  NOR _39_ (
    .A(_04_),
    .B(_13_),
    .Y(empties[2])
  );
  NOR _40_ (
    .A(_05_),
    .B(_13_),
    .Y(empties[4])
  );
  NOR _41_ (
    .A(_06_),
    .B(_13_),
    .Y(empties[3])
  );
  NOR _42_ (
    .A(_07_),
    .B(_13_),
    .Y(empties[1])
  );
  NOR _43_ (
    .A(_08_),
    .B(_13_),
    .Y(empties[0])
  );
  NOR _44_ (
    .A(almost_full0),
    .B(almost_full1),
    .Y(_14_)
  );
  NOR _45_ (
    .A(almost_full2),
    .B(almost_full3),
    .Y(_15_)
  );
  NAND _46_ (
    .A(_14_),
    .B(_15_),
    .Y(_16_)
  );
  NOR _47_ (
    .A(_08_),
    .B(_16_),
    .Y(_17_)
  );
  NAND _48_ (
    .A(_07_),
    .B(empties[0]),
    .Y(_18_)
  );
  NOR _49_ (
    .A(_16_),
    .B(_18_),
    .Y(pop1)
  );
  NAND _50_ (
    .A(empties[1]),
    .B(_17_),
    .Y(_19_)
  );
  NAND _51_ (
    .A(empty2_orange),
    .B(_06_),
    .Y(_20_)
  );
  NOR _52_ (
    .A(_19_),
    .B(_20_),
    .Y(pop3)
  );
  NOR _53_ (
    .A(empty2_orange),
    .B(_19_),
    .Y(pop2)
  );
  NAND _54_ (
    .A(_08_),
    .B(_00_),
    .Y(_21_)
  );
  NOR _55_ (
    .A(_16_),
    .B(_21_),
    .Y(pop0)
  );
  (* src = "arbitro_estruct.v:24" *)
  DFF _56_ (
    .C(clk),
    .D(_00_),
    .Q(push)
  );
endmodule
