/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "Contador_estruct.v:1" *)
module Contador_estruct(data_FIFO_0, data_FIFO_1, data_FIFO_2, data_FIFO_3, req, clk, state, idx, valid, data_out);
  (* src = "Contador_estruct.v:17" *)
  wire [4:0] _000_;
  (* src = "Contador_estruct.v:17" *)
  wire [4:0] _001_;
  (* src = "Contador_estruct.v:17" *)
  wire [4:0] _002_;
  (* src = "Contador_estruct.v:17" *)
  wire [4:0] _003_;
  (* src = "Contador_estruct.v:43" *)
  wire [4:0] _004_;
  (* src = "Contador_estruct.v:43" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  (* src = "Contador_estruct.v:7" *)
  input clk;
  (* src = "Contador_estruct.v:14" *)
  wire [4:0] contador_0;
  (* src = "Contador_estruct.v:14" *)
  wire [4:0] contador_1;
  (* src = "Contador_estruct.v:14" *)
  wire [4:0] contador_2;
  (* src = "Contador_estruct.v:14" *)
  wire [4:0] contador_3;
  (* src = "Contador_estruct.v:2" *)
  input [9:0] data_FIFO_0;
  (* src = "Contador_estruct.v:3" *)
  input [9:0] data_FIFO_1;
  (* src = "Contador_estruct.v:4" *)
  input [9:0] data_FIFO_2;
  (* src = "Contador_estruct.v:5" *)
  input [9:0] data_FIFO_3;
  (* src = "Contador_estruct.v:11" *)
  output [4:0] data_out;
  (* src = "Contador_estruct.v:9" *)
  input [1:0] idx;
  (* src = "Contador_estruct.v:6" *)
  input req;
  (* src = "Contador_estruct.v:8" *)
  input [3:0] state;
  (* src = "Contador_estruct.v:10" *)
  output valid;
  NOT _183_ (
    .A(state[0]),
    .Y(_006_)
  );
  NOT _184_ (
    .A(idx[1]),
    .Y(_007_)
  );
  NOT _185_ (
    .A(idx[0]),
    .Y(_008_)
  );
  NOT _186_ (
    .A(contador_3[1]),
    .Y(_009_)
  );
  NOT _187_ (
    .A(contador_3[3]),
    .Y(_010_)
  );
  NOT _188_ (
    .A(contador_2[1]),
    .Y(_011_)
  );
  NOT _189_ (
    .A(contador_2[3]),
    .Y(_012_)
  );
  NOT _190_ (
    .A(contador_1[1]),
    .Y(_013_)
  );
  NOT _191_ (
    .A(contador_1[3]),
    .Y(_014_)
  );
  NOT _192_ (
    .A(contador_0[1]),
    .Y(_015_)
  );
  NOT _193_ (
    .A(contador_0[3]),
    .Y(_016_)
  );
  NOR _194_ (
    .A(state[1]),
    .B(state[3]),
    .Y(_017_)
  );
  NAND _195_ (
    .A(state[2]),
    .B(_006_),
    .Y(_018_)
  );
  NAND _196_ (
    .A(req),
    .B(_017_),
    .Y(_019_)
  );
  NOR _197_ (
    .A(_018_),
    .B(_019_),
    .Y(_005_)
  );
  NOR _198_ (
    .A(state[2]),
    .B(_006_),
    .Y(_020_)
  );
  NAND _199_ (
    .A(state[0]),
    .B(_017_),
    .Y(_021_)
  );
  NOR _200_ (
    .A(state[2]),
    .B(_021_),
    .Y(_022_)
  );
  NAND _201_ (
    .A(_017_),
    .B(_020_),
    .Y(_023_)
  );
  NOR _202_ (
    .A(idx[1]),
    .B(_008_),
    .Y(_024_)
  );
  NAND _203_ (
    .A(contador_1[0]),
    .B(_024_),
    .Y(_025_)
  );
  NOR _204_ (
    .A(idx[1]),
    .B(idx[0]),
    .Y(_026_)
  );
  NAND _205_ (
    .A(contador_0[0]),
    .B(_026_),
    .Y(_027_)
  );
  NOR _206_ (
    .A(_007_),
    .B(idx[0]),
    .Y(_028_)
  );
  NAND _207_ (
    .A(contador_2[0]),
    .B(_028_),
    .Y(_029_)
  );
  NOR _208_ (
    .A(_007_),
    .B(_008_),
    .Y(_030_)
  );
  NAND _209_ (
    .A(contador_3[0]),
    .B(_030_),
    .Y(_031_)
  );
  NAND _210_ (
    .A(_025_),
    .B(_029_),
    .Y(_032_)
  );
  NAND _211_ (
    .A(_027_),
    .B(_031_),
    .Y(_033_)
  );
  NOR _212_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NAND _213_ (
    .A(_005_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _214_ (
    .A(data_out[0]),
    .B(_005_),
    .Y(_036_)
  );
  NOT _215_ (
    .A(_036_),
    .Y(_037_)
  );
  NAND _216_ (
    .A(_035_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _217_ (
    .A(_022_),
    .B(_038_),
    .Y(_004_[0])
  );
  NAND _218_ (
    .A(contador_1[1]),
    .B(_024_),
    .Y(_039_)
  );
  NAND _219_ (
    .A(contador_0[1]),
    .B(_026_),
    .Y(_040_)
  );
  NAND _220_ (
    .A(contador_2[1]),
    .B(_028_),
    .Y(_041_)
  );
  NAND _221_ (
    .A(contador_3[1]),
    .B(_030_),
    .Y(_042_)
  );
  NAND _222_ (
    .A(_039_),
    .B(_041_),
    .Y(_043_)
  );
  NAND _223_ (
    .A(_040_),
    .B(_042_),
    .Y(_044_)
  );
  NOR _224_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _225_ (
    .A(data_out[1]),
    .B(_005_),
    .Y(_046_)
  );
  NAND _226_ (
    .A(_005_),
    .B(_045_),
    .Y(_047_)
  );
  NAND _227_ (
    .A(_023_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _228_ (
    .A(_046_),
    .B(_048_),
    .Y(_004_[1])
  );
  NAND _229_ (
    .A(contador_2[2]),
    .B(_028_),
    .Y(_049_)
  );
  NAND _230_ (
    .A(contador_1[2]),
    .B(_024_),
    .Y(_050_)
  );
  NAND _231_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _232_ (
    .A(contador_0[2]),
    .B(_026_),
    .Y(_052_)
  );
  NAND _233_ (
    .A(contador_3[2]),
    .B(_030_),
    .Y(_053_)
  );
  NAND _234_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _235_ (
    .A(_051_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _236_ (
    .A(data_out[2]),
    .B(_005_),
    .Y(_056_)
  );
  NAND _237_ (
    .A(_005_),
    .B(_055_),
    .Y(_057_)
  );
  NAND _238_ (
    .A(_023_),
    .B(_057_),
    .Y(_058_)
  );
  NOR _239_ (
    .A(_056_),
    .B(_058_),
    .Y(_004_[2])
  );
  NAND _240_ (
    .A(contador_1[3]),
    .B(_024_),
    .Y(_059_)
  );
  NAND _241_ (
    .A(contador_3[3]),
    .B(_030_),
    .Y(_060_)
  );
  NAND _242_ (
    .A(contador_2[3]),
    .B(_028_),
    .Y(_061_)
  );
  NAND _243_ (
    .A(contador_0[3]),
    .B(_026_),
    .Y(_062_)
  );
  NAND _244_ (
    .A(_059_),
    .B(_061_),
    .Y(_063_)
  );
  NAND _245_ (
    .A(_060_),
    .B(_062_),
    .Y(_064_)
  );
  NOR _246_ (
    .A(_063_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _247_ (
    .A(data_out[3]),
    .B(_005_),
    .Y(_066_)
  );
  NAND _248_ (
    .A(_005_),
    .B(_065_),
    .Y(_067_)
  );
  NAND _249_ (
    .A(_023_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _250_ (
    .A(_066_),
    .B(_068_),
    .Y(_004_[3])
  );
  NAND _251_ (
    .A(contador_2[4]),
    .B(_028_),
    .Y(_069_)
  );
  NAND _252_ (
    .A(contador_1[4]),
    .B(_024_),
    .Y(_070_)
  );
  NAND _253_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  NAND _254_ (
    .A(contador_3[4]),
    .B(_030_),
    .Y(_072_)
  );
  NAND _255_ (
    .A(contador_0[4]),
    .B(_026_),
    .Y(_073_)
  );
  NAND _256_ (
    .A(_072_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _257_ (
    .A(_071_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _258_ (
    .A(data_out[4]),
    .B(_005_),
    .Y(_076_)
  );
  NAND _259_ (
    .A(_005_),
    .B(_075_),
    .Y(_077_)
  );
  NAND _260_ (
    .A(_023_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _261_ (
    .A(_076_),
    .B(_078_),
    .Y(_004_[4])
  );
  NOR _262_ (
    .A(data_FIFO_3[6]),
    .B(data_FIFO_3[7]),
    .Y(_079_)
  );
  NOR _263_ (
    .A(data_FIFO_3[8]),
    .B(data_FIFO_3[9]),
    .Y(_080_)
  );
  NAND _264_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _265_ (
    .A(data_FIFO_3[0]),
    .B(data_FIFO_3[1]),
    .Y(_082_)
  );
  NOR _266_ (
    .A(data_FIFO_3[3]),
    .B(data_FIFO_3[4]),
    .Y(_083_)
  );
  NOR _267_ (
    .A(data_FIFO_3[2]),
    .B(data_FIFO_3[5]),
    .Y(_084_)
  );
  NAND _268_ (
    .A(_082_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _269_ (
    .A(_081_),
    .B(_085_),
    .Y(_086_)
  );
  NAND _270_ (
    .A(_083_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _271_ (
    .A(contador_3[0]),
    .B(_087_),
    .Y(_088_)
  );
  NOR _272_ (
    .A(contador_3[0]),
    .B(_087_),
    .Y(_089_)
  );
  NOR _273_ (
    .A(_022_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _274_ (
    .A(_088_),
    .B(_090_),
    .Y(_091_)
  );
  NOT _275_ (
    .A(_091_),
    .Y(_003_[0])
  );
  NOR _276_ (
    .A(_009_),
    .B(_088_),
    .Y(_092_)
  );
  NAND _277_ (
    .A(_009_),
    .B(_088_),
    .Y(_093_)
  );
  NAND _278_ (
    .A(_023_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _279_ (
    .A(_092_),
    .B(_094_),
    .Y(_003_[1])
  );
  NAND _280_ (
    .A(contador_3[2]),
    .B(_092_),
    .Y(_095_)
  );
  NOR _281_ (
    .A(contador_3[2]),
    .B(_092_),
    .Y(_096_)
  );
  NAND _282_ (
    .A(_023_),
    .B(_095_),
    .Y(_097_)
  );
  NOR _283_ (
    .A(_096_),
    .B(_097_),
    .Y(_003_[2])
  );
  NOR _284_ (
    .A(_010_),
    .B(_095_),
    .Y(_098_)
  );
  NAND _285_ (
    .A(_010_),
    .B(_095_),
    .Y(_099_)
  );
  NAND _286_ (
    .A(_023_),
    .B(_099_),
    .Y(_100_)
  );
  NOR _287_ (
    .A(_098_),
    .B(_100_),
    .Y(_003_[3])
  );
  NAND _288_ (
    .A(contador_3[4]),
    .B(_098_),
    .Y(_101_)
  );
  NOR _289_ (
    .A(contador_3[4]),
    .B(_098_),
    .Y(_102_)
  );
  NOR _290_ (
    .A(_022_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _291_ (
    .A(_101_),
    .B(_103_),
    .Y(_104_)
  );
  NOT _292_ (
    .A(_104_),
    .Y(_003_[4])
  );
  NOR _293_ (
    .A(data_FIFO_2[6]),
    .B(data_FIFO_2[7]),
    .Y(_105_)
  );
  NOR _294_ (
    .A(data_FIFO_2[8]),
    .B(data_FIFO_2[9]),
    .Y(_106_)
  );
  NAND _295_ (
    .A(_105_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _296_ (
    .A(data_FIFO_2[0]),
    .B(data_FIFO_2[1]),
    .Y(_108_)
  );
  NOR _297_ (
    .A(data_FIFO_2[3]),
    .B(data_FIFO_2[4]),
    .Y(_109_)
  );
  NOR _298_ (
    .A(data_FIFO_2[2]),
    .B(data_FIFO_2[5]),
    .Y(_110_)
  );
  NAND _299_ (
    .A(_108_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _300_ (
    .A(_107_),
    .B(_111_),
    .Y(_112_)
  );
  NAND _301_ (
    .A(_109_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _302_ (
    .A(contador_2[0]),
    .B(_113_),
    .Y(_114_)
  );
  NOR _303_ (
    .A(contador_2[0]),
    .B(_113_),
    .Y(_115_)
  );
  NOR _304_ (
    .A(_022_),
    .B(_115_),
    .Y(_116_)
  );
  NAND _305_ (
    .A(_114_),
    .B(_116_),
    .Y(_117_)
  );
  NOT _306_ (
    .A(_117_),
    .Y(_002_[0])
  );
  NOR _307_ (
    .A(_011_),
    .B(_114_),
    .Y(_118_)
  );
  NAND _308_ (
    .A(_011_),
    .B(_114_),
    .Y(_119_)
  );
  NAND _309_ (
    .A(_023_),
    .B(_119_),
    .Y(_120_)
  );
  NOR _310_ (
    .A(_118_),
    .B(_120_),
    .Y(_002_[1])
  );
  NAND _311_ (
    .A(contador_2[2]),
    .B(_118_),
    .Y(_121_)
  );
  NOR _312_ (
    .A(contador_2[2]),
    .B(_118_),
    .Y(_122_)
  );
  NAND _313_ (
    .A(_023_),
    .B(_121_),
    .Y(_123_)
  );
  NOR _314_ (
    .A(_122_),
    .B(_123_),
    .Y(_002_[2])
  );
  NOR _315_ (
    .A(_012_),
    .B(_121_),
    .Y(_124_)
  );
  NAND _316_ (
    .A(_012_),
    .B(_121_),
    .Y(_125_)
  );
  NAND _317_ (
    .A(_023_),
    .B(_125_),
    .Y(_126_)
  );
  NOR _318_ (
    .A(_124_),
    .B(_126_),
    .Y(_002_[3])
  );
  NAND _319_ (
    .A(contador_2[4]),
    .B(_124_),
    .Y(_127_)
  );
  NOR _320_ (
    .A(contador_2[4]),
    .B(_124_),
    .Y(_128_)
  );
  NOR _321_ (
    .A(_022_),
    .B(_128_),
    .Y(_129_)
  );
  NAND _322_ (
    .A(_127_),
    .B(_129_),
    .Y(_130_)
  );
  NOT _323_ (
    .A(_130_),
    .Y(_002_[4])
  );
  NOR _324_ (
    .A(data_FIFO_1[6]),
    .B(data_FIFO_1[7]),
    .Y(_131_)
  );
  NOR _325_ (
    .A(data_FIFO_1[8]),
    .B(data_FIFO_1[9]),
    .Y(_132_)
  );
  NAND _326_ (
    .A(_131_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _327_ (
    .A(data_FIFO_1[0]),
    .B(data_FIFO_1[1]),
    .Y(_134_)
  );
  NOR _328_ (
    .A(data_FIFO_1[3]),
    .B(data_FIFO_1[4]),
    .Y(_135_)
  );
  NOR _329_ (
    .A(data_FIFO_1[2]),
    .B(data_FIFO_1[5]),
    .Y(_136_)
  );
  NAND _330_ (
    .A(_134_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _331_ (
    .A(_133_),
    .B(_137_),
    .Y(_138_)
  );
  NAND _332_ (
    .A(_135_),
    .B(_138_),
    .Y(_139_)
  );
  NAND _333_ (
    .A(contador_1[0]),
    .B(_139_),
    .Y(_140_)
  );
  NOR _334_ (
    .A(contador_1[0]),
    .B(_139_),
    .Y(_141_)
  );
  NOR _335_ (
    .A(_022_),
    .B(_141_),
    .Y(_142_)
  );
  NAND _336_ (
    .A(_140_),
    .B(_142_),
    .Y(_143_)
  );
  NOT _337_ (
    .A(_143_),
    .Y(_001_[0])
  );
  NOR _338_ (
    .A(_013_),
    .B(_140_),
    .Y(_144_)
  );
  NAND _339_ (
    .A(_013_),
    .B(_140_),
    .Y(_145_)
  );
  NAND _340_ (
    .A(_023_),
    .B(_145_),
    .Y(_146_)
  );
  NOR _341_ (
    .A(_144_),
    .B(_146_),
    .Y(_001_[1])
  );
  NAND _342_ (
    .A(contador_1[2]),
    .B(_144_),
    .Y(_147_)
  );
  NOR _343_ (
    .A(contador_1[2]),
    .B(_144_),
    .Y(_148_)
  );
  NAND _344_ (
    .A(_023_),
    .B(_147_),
    .Y(_149_)
  );
  NOR _345_ (
    .A(_148_),
    .B(_149_),
    .Y(_001_[2])
  );
  NOR _346_ (
    .A(_014_),
    .B(_147_),
    .Y(_150_)
  );
  NAND _347_ (
    .A(_014_),
    .B(_147_),
    .Y(_151_)
  );
  NAND _348_ (
    .A(_023_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _349_ (
    .A(_150_),
    .B(_152_),
    .Y(_001_[3])
  );
  NAND _350_ (
    .A(contador_1[4]),
    .B(_150_),
    .Y(_153_)
  );
  NOR _351_ (
    .A(contador_1[4]),
    .B(_150_),
    .Y(_154_)
  );
  NOR _352_ (
    .A(_022_),
    .B(_154_),
    .Y(_155_)
  );
  NAND _353_ (
    .A(_153_),
    .B(_155_),
    .Y(_156_)
  );
  NOT _354_ (
    .A(_156_),
    .Y(_001_[4])
  );
  NOR _355_ (
    .A(data_FIFO_0[8]),
    .B(data_FIFO_0[9]),
    .Y(_157_)
  );
  NOR _356_ (
    .A(data_FIFO_0[0]),
    .B(data_FIFO_0[1]),
    .Y(_158_)
  );
  NAND _357_ (
    .A(_157_),
    .B(_158_),
    .Y(_159_)
  );
  NOR _358_ (
    .A(data_FIFO_0[2]),
    .B(data_FIFO_0[3]),
    .Y(_160_)
  );
  NOR _359_ (
    .A(data_FIFO_0[5]),
    .B(data_FIFO_0[6]),
    .Y(_161_)
  );
  NOR _360_ (
    .A(data_FIFO_0[4]),
    .B(data_FIFO_0[7]),
    .Y(_162_)
  );
  NAND _361_ (
    .A(_160_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _362_ (
    .A(_159_),
    .B(_163_),
    .Y(_164_)
  );
  NAND _363_ (
    .A(_161_),
    .B(_164_),
    .Y(_165_)
  );
  NAND _364_ (
    .A(contador_0[0]),
    .B(_165_),
    .Y(_166_)
  );
  NOR _365_ (
    .A(contador_0[0]),
    .B(_165_),
    .Y(_167_)
  );
  NOR _366_ (
    .A(_022_),
    .B(_167_),
    .Y(_168_)
  );
  NAND _367_ (
    .A(_166_),
    .B(_168_),
    .Y(_169_)
  );
  NOT _368_ (
    .A(_169_),
    .Y(_000_[0])
  );
  NOR _369_ (
    .A(_015_),
    .B(_166_),
    .Y(_170_)
  );
  NAND _370_ (
    .A(_015_),
    .B(_166_),
    .Y(_171_)
  );
  NAND _371_ (
    .A(_023_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _372_ (
    .A(_170_),
    .B(_172_),
    .Y(_000_[1])
  );
  NAND _373_ (
    .A(contador_0[2]),
    .B(_170_),
    .Y(_173_)
  );
  NOR _374_ (
    .A(contador_0[2]),
    .B(_170_),
    .Y(_174_)
  );
  NAND _375_ (
    .A(_023_),
    .B(_173_),
    .Y(_175_)
  );
  NOR _376_ (
    .A(_174_),
    .B(_175_),
    .Y(_000_[2])
  );
  NOR _377_ (
    .A(_016_),
    .B(_173_),
    .Y(_176_)
  );
  NAND _378_ (
    .A(_016_),
    .B(_173_),
    .Y(_177_)
  );
  NAND _379_ (
    .A(_023_),
    .B(_177_),
    .Y(_178_)
  );
  NOR _380_ (
    .A(_176_),
    .B(_178_),
    .Y(_000_[3])
  );
  NAND _381_ (
    .A(contador_0[4]),
    .B(_176_),
    .Y(_179_)
  );
  NOR _382_ (
    .A(contador_0[4]),
    .B(_176_),
    .Y(_180_)
  );
  NOR _383_ (
    .A(_022_),
    .B(_180_),
    .Y(_181_)
  );
  NAND _384_ (
    .A(_179_),
    .B(_181_),
    .Y(_182_)
  );
  NOT _385_ (
    .A(_182_),
    .Y(_000_[4])
  );
  (* src = "Contador_estruct.v:43" *)
  DFF _386_ (
    .C(clk),
    .D(_005_),
    .Q(valid)
  );
  (* src = "Contador_estruct.v:43" *)
  DFF _387_ (
    .C(clk),
    .D(_004_[0]),
    .Q(data_out[0])
  );
  (* src = "Contador_estruct.v:43" *)
  DFF _388_ (
    .C(clk),
    .D(_004_[1]),
    .Q(data_out[1])
  );
  (* src = "Contador_estruct.v:43" *)
  DFF _389_ (
    .C(clk),
    .D(_004_[2]),
    .Q(data_out[2])
  );
  (* src = "Contador_estruct.v:43" *)
  DFF _390_ (
    .C(clk),
    .D(_004_[3]),
    .Q(data_out[3])
  );
  (* src = "Contador_estruct.v:43" *)
  DFF _391_ (
    .C(clk),
    .D(_004_[4]),
    .Q(data_out[4])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _392_ (
    .C(clk),
    .D(_000_[0]),
    .Q(contador_0[0])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _393_ (
    .C(clk),
    .D(_000_[1]),
    .Q(contador_0[1])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _394_ (
    .C(clk),
    .D(_000_[2]),
    .Q(contador_0[2])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _395_ (
    .C(clk),
    .D(_000_[3]),
    .Q(contador_0[3])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _396_ (
    .C(clk),
    .D(_000_[4]),
    .Q(contador_0[4])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _397_ (
    .C(clk),
    .D(_001_[0]),
    .Q(contador_1[0])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _398_ (
    .C(clk),
    .D(_001_[1]),
    .Q(contador_1[1])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _399_ (
    .C(clk),
    .D(_001_[2]),
    .Q(contador_1[2])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _400_ (
    .C(clk),
    .D(_001_[3]),
    .Q(contador_1[3])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _401_ (
    .C(clk),
    .D(_001_[4]),
    .Q(contador_1[4])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _402_ (
    .C(clk),
    .D(_002_[0]),
    .Q(contador_2[0])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _403_ (
    .C(clk),
    .D(_002_[1]),
    .Q(contador_2[1])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _404_ (
    .C(clk),
    .D(_002_[2]),
    .Q(contador_2[2])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _405_ (
    .C(clk),
    .D(_002_[3]),
    .Q(contador_2[3])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _406_ (
    .C(clk),
    .D(_002_[4]),
    .Q(contador_2[4])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _407_ (
    .C(clk),
    .D(_003_[0]),
    .Q(contador_3[0])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _408_ (
    .C(clk),
    .D(_003_[1]),
    .Q(contador_3[1])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _409_ (
    .C(clk),
    .D(_003_[2]),
    .Q(contador_3[2])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _410_ (
    .C(clk),
    .D(_003_[3]),
    .Q(contador_3[3])
  );
  (* src = "Contador_estruct.v:17" *)
  DFF _411_ (
    .C(clk),
    .D(_003_[4]),
    .Q(contador_3[4])
  );
endmodule
